#!/bin/bash

#
# This is more or less lifted from Web.pm's Makefile, and won't work for
# anyone else unless they happen to put perl6 in /opt/rakudo/
#
env PERL6LIB=lib prove -e /opt/rakudo/perl6 -r t
